import { storage } from "./storage";

export async function seedSampleUsers() {
  try {
    const sampleUsers = [
      {
        email: "sarah.chen@stakventures.com",
        firstName: "Sarah",
        lastName: "Chen", 
        title: "Principal at STAK Ventures",
        company: "STAK Ventures",
        bio: "Early-stage investor focused on climate tech and sustainable energy solutions.",
        location: "San Francisco, CA",
        industries: ["Climate Tech", "Energy"],
        skills: ["Investment Strategy", "Due Diligence"],
        networkingGoal: "Looking to connect with innovative climate solution founders.",
        meetingPreference: "In-person preferred",
        communicationStyle: "analytical",
        meetingStyle: "in-person",
        availabilityTimezone: "PST",
        preferredMeetingTimes: ["Morning"],
        investmentInterests: ["Climate Tech"],
        fundingStage: "seed",
        dealSizeRange: "$1M-$10M",
        geographicFocus: ["North America"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "david.kim@innovateco.com",
        firstName: "David",
        lastName: "Kim",
        title: "CEO & Co-founder",
        company: "InnovateCo",
        bio: "Serial entrepreneur building AI-powered healthcare solutions.",
        location: "Boston, MA", 
        industries: ["Healthcare", "AI/ML"],
        skills: ["Product Strategy", "Regulatory Affairs"],
        networkingGoal: "Seeking strategic investors for our diagnostic platform.",
        meetingPreference: "Flexible",
        communicationStyle: "results-oriented",
        meetingStyle: "hybrid",
        availabilityTimezone: "EST",
        preferredMeetingTimes: ["Afternoon"],
        investmentInterests: ["Healthcare Tech"],
        fundingStage: "series-a",
        dealSizeRange: "$10M-$25M",
        geographicFocus: ["North America"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "maria.rodriguez@futuretech.vc",
        firstName: "Maria",
        lastName: "Rodriguez",
        title: "Managing Partner",
        company: "FutureTech Ventures",
        bio: "Leading venture capitalist specializing in B2B SaaS.",
        location: "Austin, TX",
        industries: ["Enterprise SaaS", "Infrastructure"],
        skills: ["Venture Capital", "Go-to-Market Strategy"],
        networkingGoal: "Seeking exceptional B2B SaaS founders.",
        meetingPreference: "In-person when traveling",
        communicationStyle: "direct",
        meetingStyle: "in-person",
        availabilityTimezone: "CST",
        preferredMeetingTimes: ["Morning"],
        investmentInterests: ["B2B SaaS"],
        fundingStage: "series-a",
        dealSizeRange: "$15M-$50M",
        geographicFocus: ["North America"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "alex.thompson@carboncapture.ai",
        firstName: "Alex",
        lastName: "Thompson",
        title: "Co-founder & Head of Engineering",
        company: "CarbonCapture AI",
        bio: "Machine learning engineer building AI systems for carbon capture.",
        location: "Seattle, WA",
        industries: ["Climate Tech", "AI/ML"],
        skills: ["Machine Learning", "Systems Engineering"],
        networkingGoal: "Looking for technical co-founders and climate tech investors.",
        meetingPreference: "Technical demos in-person",
        communicationStyle: "technical",
        meetingStyle: "hybrid",
        availabilityTimezone: "PST",
        preferredMeetingTimes: ["Morning"],
        investmentInterests: ["Climate Tech"],
        fundingStage: "seed",
        dealSizeRange: "$5M-$15M",
        geographicFocus: ["North America"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "lisa.wang@greentech.io",
        firstName: "Lisa",
        lastName: "Wang",
        title: "Founder & CTO",
        company: "GreenTech Solutions",
        bio: "Deep tech founder developing next-generation battery technologies.",
        location: "Palo Alto, CA",
        industries: ["Battery Technology", "Renewable Energy"],
        skills: ["Technical Leadership", "R&D Strategy"],
        networkingGoal: "Connecting with deep tech investors and energy partners.",
        meetingPreference: "Technical discussions in-person",
        communicationStyle: "analytical",
        meetingStyle: "hybrid",
        availabilityTimezone: "PST",
        preferredMeetingTimes: ["Afternoon"],
        investmentInterests: ["Battery Tech"],
        fundingStage: "series-b",
        dealSizeRange: "$25M+",
        geographicFocus: ["North America"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "michael.foster@nexgenvc.com",
        firstName: "Michael",
        lastName: "Foster",
        title: "Partner",
        company: "NexGen Ventures",
        bio: "Fintech investor with expertise in digital banking and payment solutions.",
        location: "New York, NY",
        industries: ["Fintech", "Digital Banking"],
        skills: ["Financial Analysis", "Risk Assessment"],
        networkingGoal: "Looking for innovative fintech startups disrupting traditional banking.",
        meetingPreference: "In-person preferred",
        communicationStyle: "analytical",
        meetingStyle: "in-person",
        availabilityTimezone: "EST",
        preferredMeetingTimes: ["Morning"],
        investmentInterests: ["Fintech"],
        fundingStage: "seed",
        dealSizeRange: "$2M-$10M",
        geographicFocus: ["North America"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "jennifer.lee@biotech.startup",
        firstName: "Jennifer",
        lastName: "Lee",
        title: "Founder & CEO",
        company: "BioInnovate Labs",
        bio: "Biotech entrepreneur developing personalized medicine solutions using AI.",
        location: "San Diego, CA",
        industries: ["Biotech", "Healthcare"],
        skills: ["Biotech Research", "Business Development"],
        networkingGoal: "Seeking biotech investors and pharmaceutical partnerships.",
        meetingPreference: "Flexible",
        communicationStyle: "results-oriented",
        meetingStyle: "hybrid",
        availabilityTimezone: "PST",
        preferredMeetingTimes: ["Afternoon"],
        investmentInterests: ["Biotech"],
        fundingStage: "series-a",
        dealSizeRange: "$15M-$30M",
        geographicFocus: ["North America"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "robert.davis@edtech.ventures",
        firstName: "Robert",
        lastName: "Davis",
        title: "Managing Director",
        company: "EdTech Ventures",
        bio: "Education technology investor focused on K-12 and higher education solutions.",
        location: "Chicago, IL",
        industries: ["EdTech", "Education"],
        skills: ["Educational Strategy", "Market Analysis"],
        networkingGoal: "Connecting with EdTech founders transforming learning experiences.",
        meetingPreference: "Virtual meetings preferred",
        communicationStyle: "collaborative",
        meetingStyle: "virtual",
        availabilityTimezone: "CST",
        preferredMeetingTimes: ["Afternoon"],
        investmentInterests: ["EdTech"],
        fundingStage: "seed",
        dealSizeRange: "$1M-$8M",
        geographicFocus: ["North America"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "amanda.wilson@cybersec.co",
        firstName: "Amanda",
        lastName: "Wilson",
        title: "Co-founder & CSO",
        company: "CyberSec Solutions",
        bio: "Cybersecurity expert building next-gen threat detection platforms.",
        location: "Washington, DC",
        industries: ["Cybersecurity", "Enterprise Software"],
        skills: ["Security Architecture", "Threat Analysis"],
        networkingGoal: "Looking for enterprise security investors and government partnerships.",
        meetingPreference: "Secure locations preferred",
        communicationStyle: "technical",
        meetingStyle: "in-person",
        availabilityTimezone: "EST",
        preferredMeetingTimes: ["Morning"],
        investmentInterests: ["Cybersecurity"],
        fundingStage: "series-a",
        dealSizeRange: "$10M-$20M",
        geographicFocus: ["North America"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "carlos.martinez@spactech.ventures",
        firstName: "Carlos",
        lastName: "Martinez",
        title: "Principal",
        company: "SpacTech Ventures",
        bio: "Aerospace and defense technology investor with military background.",
        location: "Los Angeles, CA",
        industries: ["Aerospace", "Defense Tech"],
        skills: ["Aerospace Engineering", "Defense Strategy"],
        networkingGoal: "Seeking aerospace startups with commercial and defense applications.",
        meetingPreference: "In-person for technical demos",
        communicationStyle: "direct",
        meetingStyle: "in-person",
        availabilityTimezone: "PST",
        preferredMeetingTimes: ["Morning"],
        investmentInterests: ["Aerospace"],
        fundingStage: "seed",
        dealSizeRange: "$5M-$15M",
        geographicFocus: ["North America"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "emily.brown@agritech.io",
        firstName: "Emily",
        lastName: "Brown",
        title: "Founder & CEO",
        company: "AgriTech Innovations",
        bio: "Agricultural technology entrepreneur developing precision farming solutions.",
        location: "Des Moines, IA",
        industries: ["AgTech", "Sustainability"],
        skills: ["Agricultural Science", "IoT Systems"],
        networkingGoal: "Connecting with agtech investors and farming industry partners.",
        meetingPreference: "Farm visits welcome",
        communicationStyle: "practical",
        meetingStyle: "in-person",
        availabilityTimezone: "CST",
        preferredMeetingTimes: ["Morning"],
        investmentInterests: ["AgTech"],
        fundingStage: "seed",
        dealSizeRange: "$3M-$12M",
        geographicFocus: ["North America"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "kevin.garcia@proptech.fund",
        firstName: "Kevin",
        lastName: "Garcia",
        title: "Investment Manager",
        company: "PropTech Fund",
        bio: "Real estate technology investor focused on residential and commercial solutions.",
        location: "Miami, FL",
        industries: ["PropTech", "Real Estate"],
        skills: ["Real Estate Analysis", "Market Research"],
        networkingGoal: "Looking for PropTech startups revolutionizing real estate transactions.",
        meetingPreference: "Property visits preferred",
        communicationStyle: "relationship-focused",
        meetingStyle: "in-person",
        availabilityTimezone: "EST",
        preferredMeetingTimes: ["Afternoon"],
        investmentInterests: ["PropTech"],
        fundingStage: "series-a",
        dealSizeRange: "$8M-$25M",
        geographicFocus: ["North America"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "rachel.kim@retailtech.ventures",
        firstName: "Rachel",
        lastName: "Kim",
        title: "Founder & CEO",
        company: "RetailTech Solutions",
        bio: "Retail technology entrepreneur building omnichannel customer experience platforms.",
        location: "San Francisco, CA",
        industries: ["RetailTech", "E-commerce"],
        skills: ["Retail Strategy", "Customer Experience"],
        networkingGoal: "Seeking retail tech investors and brand partnerships.",
        meetingPreference: "Retail showrooms preferred",
        communicationStyle: "creative",
        meetingStyle: "hybrid",
        availabilityTimezone: "PST",
        preferredMeetingTimes: ["Afternoon"],
        investmentInterests: ["RetailTech"],
        fundingStage: "series-a",
        dealSizeRange: "$12M-$30M",
        geographicFocus: ["North America"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "james.taylor@foodtech.capital",
        firstName: "James",
        lastName: "Taylor",
        title: "Partner",
        company: "FoodTech Capital",
        bio: "Food and beverage technology investor with supply chain expertise.",
        location: "Portland, OR",
        industries: ["FoodTech", "Supply Chain"],
        skills: ["Supply Chain Management", "Food Safety"],
        networkingGoal: "Connecting with FoodTech startups improving sustainability and efficiency.",
        meetingPreference: "Kitchen visits welcome",
        communicationStyle: "practical",
        meetingStyle: "in-person",
        availabilityTimezone: "PST",
        preferredMeetingTimes: ["Morning"],
        investmentInterests: ["FoodTech"],
        fundingStage: "seed",
        dealSizeRange: "$2M-$10M",
        geographicFocus: ["North America"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "sophia.zhang@medtech.innovations",
        firstName: "Sophia",
        lastName: "Zhang",
        title: "Co-founder & CTO",
        company: "MedTech Innovations",
        bio: "Medical device engineer developing minimally invasive surgical technologies.",
        location: "Boston, MA",
        industries: ["MedTech", "Healthcare"],
        skills: ["Medical Device Design", "Regulatory Affairs"],
        networkingGoal: "Looking for MedTech investors and hospital partnerships.",
        meetingPreference: "Clinical settings preferred",
        communicationStyle: "technical",
        meetingStyle: "in-person",
        availabilityTimezone: "EST",
        preferredMeetingTimes: ["Morning"],
        investmentInterests: ["MedTech"],
        fundingStage: "series-a",
        dealSizeRange: "$15M-$40M",
        geographicFocus: ["North America"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "daniel.johnson@mobility.ventures",
        firstName: "Daniel",
        lastName: "Johnson",
        title: "Principal",
        company: "Mobility Ventures",
        bio: "Transportation and mobility investor focused on autonomous and electric vehicles.",
        location: "Detroit, MI",
        industries: ["Mobility", "Automotive"],
        skills: ["Automotive Engineering", "Transportation Strategy"],
        networkingGoal: "Seeking mobility startups with breakthrough transportation technologies.",
        meetingPreference: "Test drives welcome",
        communicationStyle: "technical",
        meetingStyle: "in-person",
        availabilityTimezone: "EST",
        preferredMeetingTimes: ["Afternoon"],
        investmentInterests: ["Mobility"],
        fundingStage: "series-a",
        dealSizeRange: "$20M-$50M",
        geographicFocus: ["North America"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "natalie.white@consumertech.fund",
        firstName: "Natalie",
        lastName: "White",
        title: "Investment Director",
        company: "ConsumerTech Fund",
        bio: "Consumer technology investor with brand building and marketing expertise.",
        location: "San Francisco, CA",
        industries: ["Consumer Tech", "Brand Strategy"],
        skills: ["Brand Development", "Consumer Research"],
        networkingGoal: "Looking for consumer tech startups with strong brand potential.",
        meetingPreference: "Showroom presentations preferred",
        communicationStyle: "creative",
        meetingStyle: "hybrid",
        availabilityTimezone: "PST",
        preferredMeetingTimes: ["Afternoon"],
        investmentInterests: ["Consumer Tech"],
        fundingStage: "seed",
        dealSizeRange: "$3M-$15M",
        geographicFocus: ["North America"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "christopher.lee@energytech.capital",
        firstName: "Christopher",
        lastName: "Lee",
        title: "Managing Partner",
        company: "EnergyTech Capital",
        bio: "Energy sector investor specializing in grid modernization and storage solutions.",
        location: "Houston, TX",
        industries: ["Energy", "Grid Technology"],
        skills: ["Energy Markets", "Grid Infrastructure"],
        networkingGoal: "Connecting with energy tech startups modernizing the electrical grid.",
        meetingPreference: "Power plant visits welcome",
        communicationStyle: "analytical",
        meetingStyle: "in-person",
        availabilityTimezone: "CST",
        preferredMeetingTimes: ["Morning"],
        investmentInterests: ["Energy Tech"],
        fundingStage: "series-a",
        dealSizeRange: "$25M-$75M",
        geographicFocus: ["North America"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "lauren.davis@legaltech.ventures",
        firstName: "Lauren",
        lastName: "Davis",
        title: "Founder & CEO",
        company: "LegalTech Solutions",
        bio: "Legal technology entrepreneur automating contract analysis and compliance.",
        location: "New York, NY",
        industries: ["LegalTech", "Enterprise Software"],
        skills: ["Legal Operations", "Contract Management"],
        networkingGoal: "Seeking LegalTech investors and law firm partnerships.",
        meetingPreference: "Law office meetings preferred",
        communicationStyle: "analytical",
        meetingStyle: "in-person",
        availabilityTimezone: "EST",
        preferredMeetingTimes: ["Morning"],
        investmentInterests: ["LegalTech"],
        fundingStage: "series-a",
        dealSizeRange: "$10M-$25M",
        geographicFocus: ["North America"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "ryan.miller@insuretech.fund",
        firstName: "Ryan",
        lastName: "Miller",
        title: "Partner",
        company: "InsureTech Fund",
        bio: "Insurance technology investor with actuarial science background.",
        location: "Hartford, CT",
        industries: ["InsureTech", "Financial Services"],
        skills: ["Actuarial Science", "Risk Modeling"],
        networkingGoal: "Looking for InsureTech startups transforming risk assessment.",
        meetingPreference: "Office meetings preferred",
        communicationStyle: "analytical",
        meetingStyle: "in-person",
        availabilityTimezone: "EST",
        preferredMeetingTimes: ["Afternoon"],
        investmentInterests: ["InsureTech"],
        fundingStage: "seed",
        dealSizeRange: "$5M-$20M",
        geographicFocus: ["North America"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "michelle.anderson@hrtech.capital",
        firstName: "Michelle",
        lastName: "Anderson",
        title: "Co-founder & CEO",
        company: "HRTech Innovations",
        bio: "Human resources technology entrepreneur building AI-powered recruiting platforms.",
        location: "Austin, TX",
        industries: ["HRTech", "AI/ML"],
        skills: ["Human Resources", "Talent Acquisition"],
        networkingGoal: "Connecting with HRTech investors and enterprise HR partnerships.",
        meetingPreference: "Office environment preferred",
        communicationStyle: "collaborative",
        meetingStyle: "hybrid",
        availabilityTimezone: "CST",
        preferredMeetingTimes: ["Afternoon"],
        investmentInterests: ["HRTech"],
        fundingStage: "series-a",
        dealSizeRange: "$8M-$20M",
        geographicFocus: ["North America"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "andrew.wilson@healthtech.ventures",
        firstName: "Andrew",
        lastName: "Wilson",
        title: "Principal",
        company: "HealthTech Ventures",
        bio: "Digital health investor focused on telemedicine and remote patient monitoring.",
        location: "Nashville, TN",
        industries: ["Digital Health", "Telemedicine"],
        skills: ["Healthcare Strategy", "Digital Transformation"],
        networkingGoal: "Seeking digital health startups improving patient outcomes.",
        meetingPreference: "Hospital visits welcome",
        communicationStyle: "empathetic",
        meetingStyle: "hybrid",
        availabilityTimezone: "CST",
        preferredMeetingTimes: ["Morning"],
        investmentInterests: ["Digital Health"],
        fundingStage: "seed",
        dealSizeRange: "$3M-$15M",
        geographicFocus: ["North America"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "jessica.thomas@sportech.fund",
        firstName: "Jessica",
        lastName: "Thomas",
        title: "Investment Manager",
        company: "SportTech Fund",
        bio: "Sports technology investor with professional athletics background.",
        location: "Phoenix, AZ",
        industries: ["SportTech", "Media"],
        skills: ["Sports Analytics", "Performance Technology"],
        networkingGoal: "Looking for SportTech startups enhancing athletic performance.",
        meetingPreference: "Sports facilities preferred",
        communicationStyle: "competitive",
        meetingStyle: "in-person",
        availabilityTimezone: "MST",
        preferredMeetingTimes: ["Morning"],
        investmentInterests: ["SportTech"],
        fundingStage: "seed",
        dealSizeRange: "$2M-$10M",
        geographicFocus: ["North America"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "brian.garcia@gamintech.ventures",
        firstName: "Brian",
        lastName: "Garcia",
        title: "Founder & CEO",
        company: "GamingTech Studios",
        bio: "Gaming technology entrepreneur developing immersive VR/AR gaming experiences.",
        location: "Los Angeles, CA",
        industries: ["Gaming", "VR/AR"],
        skills: ["Game Development", "Virtual Reality"],
        networkingGoal: "Seeking gaming investors and entertainment industry partnerships.",
        meetingPreference: "Gaming studios preferred",
        communicationStyle: "creative",
        meetingStyle: "in-person",
        availabilityTimezone: "PST",
        preferredMeetingTimes: ["Evening"],
        investmentInterests: ["Gaming"],
        fundingStage: "series-a",
        dealSizeRange: "$10M-$30M",
        geographicFocus: ["North America"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "samantha.martinez@traveltech.capital",
        firstName: "Samantha",
        lastName: "Martinez",
        title: "Partner",
        company: "TravelTech Capital",
        bio: "Travel technology investor with hospitality industry expertise.",
        location: "Las Vegas, NV",
        industries: ["Travel Tech", "Hospitality"],
        skills: ["Hospitality Management", "Travel Operations"],
        networkingGoal: "Connecting with travel tech startups transforming guest experiences.",
        meetingPreference: "Hotel meetings preferred",
        communicationStyle: "relationship-focused",
        meetingStyle: "in-person",
        availabilityTimezone: "PST",
        preferredMeetingTimes: ["Afternoon"],
        investmentInterests: ["Travel Tech"],
        fundingStage: "seed",
        dealSizeRange: "$3M-$12M",
        geographicFocus: ["North America"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "tyler.rodriguez@martech.ventures",
        firstName: "Tyler",
        lastName: "Rodriguez",
        title: "Co-founder & CTO",
        company: "MarTech Solutions",
        bio: "Marketing technology entrepreneur building AI-powered customer engagement platforms.",
        location: "Atlanta, GA",
        industries: ["MarTech", "AI/ML"],
        skills: ["Marketing Technology", "Customer Analytics"],
        networkingGoal: "Looking for MarTech investors and enterprise marketing partnerships.",
        meetingPreference: "Office presentations preferred",
        communicationStyle: "data-driven",
        meetingStyle: "hybrid",
        availabilityTimezone: "EST",
        preferredMeetingTimes: ["Afternoon"],
        investmentInterests: ["MarTech"],
        fundingStage: "series-a",
        dealSizeRange: "$8M-$25M",
        geographicFocus: ["North America"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "nicole.jackson@supplytech.fund",
        firstName: "Nicole",
        lastName: "Jackson",
        title: "Managing Director",
        company: "SupplyTech Fund",
        bio: "Supply chain technology investor with logistics industry background.",
        location: "Memphis, TN",
        industries: ["Supply Chain", "Logistics"],
        skills: ["Supply Chain Optimization", "Logistics Management"],
        networkingGoal: "Seeking supply chain startups improving efficiency and transparency.",
        meetingPreference: "Warehouse visits welcome",
        communicationStyle: "practical",
        meetingStyle: "in-person",
        availabilityTimezone: "CST",
        preferredMeetingTimes: ["Morning"],
        investmentInterests: ["Supply Chain"],
        fundingStage: "series-a",
        dealSizeRange: "$15M-$40M",
        geographicFocus: ["North America"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "gregory.lewis@watertech.ventures",
        firstName: "Gregory",
        lastName: "Lewis",
        title: "Founder & CEO",
        company: "WaterTech Solutions",
        bio: "Water technology entrepreneur developing advanced filtration and purification systems.",
        location: "Denver, CO",
        industries: ["Water Tech", "Environmental"],
        skills: ["Environmental Engineering", "Water Treatment"],
        networkingGoal: "Connecting with environmental tech investors and municipal partnerships.",
        meetingPreference: "Treatment facility visits preferred",
        communicationStyle: "technical",
        meetingStyle: "in-person",
        availabilityTimezone: "MST",
        preferredMeetingTimes: ["Morning"],
        investmentInterests: ["Water Tech"],
        fundingStage: "seed",
        dealSizeRange: "$5M-$20M",
        geographicFocus: ["North America"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "stephanie.clark@socialtech.capital",
        firstName: "Stephanie",
        lastName: "Clark",
        title: "Investment Director",
        company: "SocialTech Capital",
        bio: "Social impact technology investor focused on education and healthcare access.",
        location: "Washington, DC",
        industries: ["Social Impact", "EdTech"],
        skills: ["Impact Investing", "Social Entrepreneurship"],
        networkingGoal: "Looking for social impact startups with measurable community benefits.",
        meetingPreference: "Community center meetings preferred",
        communicationStyle: "empathetic",
        meetingStyle: "in-person",
        availabilityTimezone: "EST",
        preferredMeetingTimes: ["Afternoon"],
        investmentInterests: ["Social Impact"],
        fundingStage: "seed",
        dealSizeRange: "$1M-$8M",
        geographicFocus: ["North America"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "jonathan.hall@blocktech.ventures",
        firstName: "Jonathan",
        lastName: "Hall",
        title: "Partner",
        company: "BlockTech Ventures",
        bio: "Blockchain technology investor with cryptocurrency and DeFi expertise.",
        location: "San Francisco, CA",
        industries: ["Blockchain", "DeFi"],
        skills: ["Blockchain Development", "Cryptocurrency"],
        networkingGoal: "Seeking blockchain startups with real-world utility applications.",
        meetingPreference: "Tech meetups preferred",
        communicationStyle: "technical",
        meetingStyle: "hybrid",
        availabilityTimezone: "PST",
        preferredMeetingTimes: ["Evening"],
        investmentInterests: ["Blockchain"],
        fundingStage: "seed",
        dealSizeRange: "$3M-$15M",
        geographicFocus: ["Global"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "ashley.young@robotech.fund",
        firstName: "Ashley",
        lastName: "Young",
        title: "Co-founder & CEO",
        company: "RoboTech Innovations",
        bio: "Robotics entrepreneur developing autonomous systems for manufacturing and logistics.",
        location: "Pittsburgh, PA",
        industries: ["Robotics", "Manufacturing"],
        skills: ["Robotics Engineering", "Automation"],
        networkingGoal: "Looking for robotics investors and manufacturing partnerships.",
        meetingPreference: "Factory floor demonstrations preferred",
        communicationStyle: "technical",
        meetingStyle: "in-person",
        availabilityTimezone: "EST",
        preferredMeetingTimes: ["Morning"],
        investmentInterests: ["Robotics"],
        fundingStage: "series-a",
        dealSizeRange: "$20M-$50M",
        geographicFocus: ["North America"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "matthew.king@quantumtech.capital",
        firstName: "Matthew",
        lastName: "King",
        title: "Principal",
        company: "QuantumTech Capital",
        bio: "Quantum computing investor with theoretical physics background.",
        location: "Cambridge, MA",
        industries: ["Quantum Computing", "Deep Tech"],
        skills: ["Quantum Physics", "Advanced Computing"],
        networkingGoal: "Seeking quantum computing startups with commercial applications.",
        meetingPreference: "Research lab meetings preferred",
        communicationStyle: "academic",
        meetingStyle: "in-person",
        availabilityTimezone: "EST",
        preferredMeetingTimes: ["Morning"],
        investmentInterests: ["Quantum Computing"],
        fundingStage: "seed",
        dealSizeRange: "$10M-$30M",
        geographicFocus: ["North America"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "kimberly.wright@spacetech.ventures",
        firstName: "Kimberly",
        lastName: "Wright",
        title: "Investment Manager",
        company: "SpaceTech Ventures",
        bio: "Space technology investor focused on satellite communications and space exploration.",
        location: "Houston, TX",
        industries: ["Space Tech", "Satellite"],
        skills: ["Aerospace Engineering", "Satellite Technology"],
        networkingGoal: "Connecting with space tech startups advancing space exploration.",
        meetingPreference: "Space center visits preferred",
        communicationStyle: "visionary",
        meetingStyle: "in-person",
        availabilityTimezone: "CST",
        preferredMeetingTimes: ["Afternoon"],
        investmentInterests: ["Space Tech"],
        fundingStage: "series-a",
        dealSizeRange: "$25M-$100M",
        geographicFocus: ["Global"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "william.lopez@nanotech.fund",
        firstName: "William",
        lastName: "Lopez",
        title: "Founder & CTO",
        company: "NanoTech Solutions",
        bio: "Nanotechnology entrepreneur developing advanced materials for electronics and medicine.",
        location: "Austin, TX",
        industries: ["Nanotechnology", "Advanced Materials"],
        skills: ["Materials Science", "Nanotechnology"],
        networkingGoal: "Looking for deep tech investors and research institution partnerships.",
        meetingPreference: "Clean room demonstrations preferred",
        communicationStyle: "technical",
        meetingStyle: "in-person",
        availabilityTimezone: "CST",
        preferredMeetingTimes: ["Morning"],
        investmentInterests: ["Nanotechnology"],
        fundingStage: "seed",
        dealSizeRange: "$8M-$25M",
        geographicFocus: ["North America"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "elizabeth.green@biocomputing.ventures",
        firstName: "Elizabeth",
        lastName: "Green",
        title: "Managing Partner",
        company: "BioComputing Ventures",
        bio: "Biocomputing investor specializing in computational biology and drug discovery.",
        location: "San Diego, CA",
        industries: ["Biocomputing", "Drug Discovery"],
        skills: ["Computational Biology", "Bioinformatics"],
        networkingGoal: "Seeking biocomputing startups revolutionizing drug development.",
        meetingPreference: "Research lab meetings preferred",
        communicationStyle: "analytical",
        meetingStyle: "in-person",
        availabilityTimezone: "PST",
        preferredMeetingTimes: ["Morning"],
        investmentInterests: ["Biocomputing"],
        fundingStage: "series-a",
        dealSizeRange: "$15M-$50M",
        geographicFocus: ["North America"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "joseph.adams@neuraltech.capital",
        firstName: "Joseph",
        lastName: "Adams",
        title: "Co-founder & CEO",
        company: "NeuralTech Innovations",
        bio: "Neural interface entrepreneur developing brain-computer interface technologies.",
        location: "Seattle, WA",
        industries: ["Neural Tech", "Medical Devices"],
        skills: ["Neuroscience", "Medical Technology"],
        networkingGoal: "Connecting with neurotechnology investors and medical device partnerships.",
        meetingPreference: "Medical facility meetings preferred",
        communicationStyle: "scientific",
        meetingStyle: "in-person",
        availabilityTimezone: "PST",
        preferredMeetingTimes: ["Afternoon"],
        investmentInterests: ["Neural Tech"],
        fundingStage: "series-a",
        dealSizeRange: "$20M-$60M",
        geographicFocus: ["North America"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "rebecca.baker@materials.ventures",
        firstName: "Rebecca",
        lastName: "Baker",
        title: "Principal",
        company: "Materials Ventures",
        bio: "Advanced materials investor with chemical engineering background.",
        location: "Wilmington, DE",
        industries: ["Advanced Materials", "Chemicals"],
        skills: ["Chemical Engineering", "Materials Development"],
        networkingGoal: "Looking for materials science startups with commercial applications.",
        meetingPreference: "Laboratory visits preferred",
        communicationStyle: "technical",
        meetingStyle: "in-person",
        availabilityTimezone: "EST",
        preferredMeetingTimes: ["Morning"],
        investmentInterests: ["Advanced Materials"],
        fundingStage: "seed",
        dealSizeRange: "$5M-$20M",
        geographicFocus: ["North America"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "charles.nelson@fusion.ventures",
        firstName: "Charles",
        lastName: "Nelson",
        title: "Investment Director",
        company: "Fusion Ventures",
        bio: "Fusion energy investor focused on breakthrough energy generation technologies.",
        location: "Oak Ridge, TN",
        industries: ["Fusion Energy", "Clean Tech"],
        skills: ["Nuclear Physics", "Energy Systems"],
        networkingGoal: "Seeking fusion energy startups with viable commercialization paths.",
        meetingPreference: "Research facility meetings preferred",
        communicationStyle: "visionary",
        meetingStyle: "in-person",
        availabilityTimezone: "EST",
        preferredMeetingTimes: ["Afternoon"],
        investmentInterests: ["Fusion Energy"],
        fundingStage: "series-a",
        dealSizeRange: "$50M-$200M",
        geographicFocus: ["Global"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "sarah.mitchell@climatetech.fund",
        firstName: "Sarah",
        lastName: "Mitchell",
        title: "Founder & CEO",
        company: "ClimateTech Solutions",
        bio: "Climate technology entrepreneur developing carbon removal and atmospheric processing systems.",
        location: "Portland, OR",
        industries: ["Climate Tech", "Carbon Removal"],
        skills: ["Environmental Science", "Atmospheric Technology"],
        networkingGoal: "Looking for climate tech investors and environmental partnerships.",
        meetingPreference: "Field demonstration sites preferred",
        communicationStyle: "mission-driven",
        meetingStyle: "in-person",
        availabilityTimezone: "PST",
        preferredMeetingTimes: ["Morning"],
        investmentInterests: ["Climate Tech"],
        fundingStage: "series-a",
        dealSizeRange: "$30M-$100M",
        geographicFocus: ["Global"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "david.carter@oceantech.ventures",
        firstName: "David",
        lastName: "Carter",
        title: "Managing Partner",
        company: "OceanTech Ventures",
        bio: "Ocean technology investor specializing in marine conservation and aquaculture.",
        location: "San Diego, CA",
        industries: ["Ocean Tech", "Marine Science"],
        skills: ["Marine Biology", "Ocean Engineering"],
        networkingGoal: "Connecting with ocean tech startups protecting marine ecosystems.",
        meetingPreference: "Oceanside meetings preferred",
        communicationStyle: "conservation-focused",
        meetingStyle: "in-person",
        availabilityTimezone: "PST",
        preferredMeetingTimes: ["Morning"],
        investmentInterests: ["Ocean Tech"],
        fundingStage: "seed",
        dealSizeRange: "$5M-$25M",
        geographicFocus: ["Global"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "jessica.murphy@bioengineering.capital",
        firstName: "Jessica",
        lastName: "Murphy",
        title: "Co-founder & CSO",
        company: "BioEngineering Capital",
        bio: "Bioengineering entrepreneur developing synthetic biology platforms for manufacturing.",
        location: "Cambridge, MA",
        industries: ["Synthetic Biology", "Bioengineering"],
        skills: ["Genetic Engineering", "Biotechnology"],
        networkingGoal: "Seeking bioengineering investors and pharmaceutical partnerships.",
        meetingPreference: "Biolab meetings preferred",
        communicationStyle: "scientific",
        meetingStyle: "in-person",
        availabilityTimezone: "EST",
        preferredMeetingTimes: ["Afternoon"],
        investmentInterests: ["Synthetic Biology"],
        fundingStage: "series-a",
        dealSizeRange: "$25M-$75M",
        geographicFocus: ["North America"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "robert.cooper@photonics.ventures",
        firstName: "Robert",
        lastName: "Cooper",
        title: "Partner",
        company: "Photonics Ventures",
        bio: "Photonics technology investor with optical engineering expertise.",
        location: "Rochester, NY",
        industries: ["Photonics", "Optical Technology"],
        skills: ["Optical Engineering", "Laser Technology"],
        networkingGoal: "Looking for photonics startups with telecommunications and medical applications.",
        meetingPreference: "Optics lab demonstrations preferred",
        communicationStyle: "technical",
        meetingStyle: "in-person",
        availabilityTimezone: "EST",
        preferredMeetingTimes: ["Morning"],
        investmentInterests: ["Photonics"],
        fundingStage: "seed",
        dealSizeRange: "$8M-$30M",
        geographicFocus: ["North America"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "amanda.reed@smartcity.fund",
        firstName: "Amanda",
        lastName: "Reed",
        title: "Investment Manager",
        company: "SmartCity Fund",
        bio: "Smart city technology investor focused on urban infrastructure and mobility solutions.",
        location: "Chicago, IL",
        industries: ["Smart Cities", "Urban Tech"],
        skills: ["Urban Planning", "Infrastructure Technology"],
        networkingGoal: "Seeking smart city startups improving urban living and sustainability.",
        meetingPreference: "City planning office meetings preferred",
        communicationStyle: "community-focused",
        meetingStyle: "in-person",
        availabilityTimezone: "CST",
        preferredMeetingTimes: ["Afternoon"],
        investmentInterests: ["Smart Cities"],
        fundingStage: "series-a",
        dealSizeRange: "$15M-$50M",
        geographicFocus: ["North America"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "kevin.bell@autonomy.ventures",
        firstName: "Kevin",
        lastName: "Bell",
        title: "Founder & CTO",
        company: "Autonomy Ventures",
        bio: "Autonomous systems entrepreneur developing AI for industrial automation and logistics.",
        location: "Pittsburgh, PA",
        industries: ["Autonomous Systems", "Industrial AI"],
        skills: ["Autonomous Navigation", "Industrial Automation"],
        networkingGoal: "Connecting with autonomous system investors and manufacturing partnerships.",
        meetingPreference: "Factory automation demos preferred",
        communicationStyle: "technical",
        meetingStyle: "in-person",
        availabilityTimezone: "EST",
        preferredMeetingTimes: ["Morning"],
        investmentInterests: ["Autonomous Systems"],
        fundingStage: "series-a",
        dealSizeRange: "$20M-$60M",
        geographicFocus: ["North America"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "lisa.ward@precision.medicine",
        firstName: "Lisa",
        lastName: "Ward",
        title: "Principal",
        company: "Precision Medicine Partners",
        bio: "Precision medicine investor specializing in genomics and personalized therapeutics.",
        location: "Research Triangle Park, NC",
        industries: ["Precision Medicine", "Genomics"],
        skills: ["Genomic Analysis", "Personalized Medicine"],
        networkingGoal: "Looking for precision medicine startups with breakthrough therapeutic approaches.",
        meetingPreference: "Research institute meetings preferred",
        communicationStyle: "evidence-based",
        meetingStyle: "in-person",
        availabilityTimezone: "EST",
        preferredMeetingTimes: ["Morning"],
        investmentInterests: ["Precision Medicine"],
        fundingStage: "series-a",
        dealSizeRange: "$30M-$100M",
        geographicFocus: ["North America"],
        profileVisible: true,
        aiMatchingConsent: true
      },
      {
        email: "thomas.torres@deeptech.capital",
        firstName: "Thomas",
        lastName: "Torres",
        title: "Managing Director",
        company: "DeepTech Capital",
        bio: "Deep technology investor with expertise in breakthrough scientific innovations.",
        location: "Stanford, CA",
        industries: ["Deep Tech", "Scientific Innovation"],
        skills: ["Technology Assessment", "Scientific Research"],
        networkingGoal: "Seeking deep tech startups with transformative scientific breakthroughs.",
        meetingPreference: "University lab meetings preferred",
        communicationStyle: "intellectual",
        meetingStyle: "in-person",
        availabilityTimezone: "PST",
        preferredMeetingTimes: ["Afternoon"],
        investmentInterests: ["Deep Tech"],
        fundingStage: "seed",
        dealSizeRange: "$10M-$50M",
        geographicFocus: ["Global"],
        profileVisible: true,
        aiMatchingConsent: true
      }
    ];

    console.log("Seeding 50 sample users...");
    
    for (const userData of sampleUsers) {
      const existingUser = await storage.getUserByEmail(userData.email);
      if (!existingUser) {
        await storage.upsertUser(userData);
        console.log(`Created user: ${userData.firstName} ${userData.lastName}`);
      } else {
        console.log(`User already exists: ${userData.firstName} ${userData.lastName}`);
      }
    }

    console.log(`Sample users seeded successfully! Total: ${sampleUsers.length} users`);
    return true;
  } catch (error) {
    console.error("Error seeding sample users:", error);
    return false;
  }
}